# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: AzureFileCopy@3
  inputs:
    SourcePath: '$(Build.ArtifactStagingDirectory)/*'
    azureSubscription: 'Visual Studio Enterprise(ebb8c1f7-917c-4740-b84b-12f5f82bfbac)'
    Destination: 'AzureBlob'
    storage: 'elstorago2'
    ContainerName: '$web'