# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      pwd
      echo 'Hello world'
      echo $(Build.ArtifactStagingDirectory)
      ls
- task: AzureCLI@2
  inputs:
    azureSubscription: 'Visual Studio Enterprise(ebb8c1f7-917c-4740-b84b-12f5f82bfbac)'
    scriptType: 'pscore'
    scriptLocation: 'inlineScript'
    inlineScript: |
      azcopy --version
      az storage blob upload -c $web -f $(Build.ArtifactStagingDirectory)/* -n https://elstorago2.blob.core.windows.net/ --acount-name elstorago2
